### ISSUE TITLE
LTCGI working in editor, but does not show in upload. 

### ISSUE THREAD

**Issue by Roll675** [PiMaker/ltcgi#1]
LTCGI is not showing any console error logs and is working in editor, but when uploaded to VRChat it is not showing reflections / GI after importing Audio Link. 

I have yet to figure out what causes this.

**Comment by PiMaker** [comment]
Does it work in Play Mode with CyanEmu?

**Comment by Roll675** [comment]
Closed issue. We talked in Discord and found the issue!

**Comment by PiMaker** [comment]
For reference, the issue was with EditorOnly objects in the scene.  
This is fixed in 459b08a2364d9863ad66ece62432276c2ffdf27d.
