### ISSUE TITLE
No UdonSharpBehaviour class found in script file

### ISSUE THREAD

**Issue by dark-swordsman** [PiMaker/ltcgi#11]
I am trying to use the USharpVideoAdapter, but the script has this error. Tried to diagnose but I can not figure out how to solve it.

Double checked UdonSharp, USharpVideo, and the VRCSDK.

`
Assets/_pi_/_LTCGI/Adapters/LTCGI_USharpVideoAdapter.cs(63,6): System.Exception: No UdonSharpBehaviour class found in script file, you must define an UdonSharpBehaviour class in a script referenced by an UdonSharpProgramAsse
`

![image](https://user-images.githubusercontent.com/7909209/212965754-84007440-85d6-4b70-8cad-8c2f867f9cd6.png)

**Comment by dark-swordsman** [comment]
I realized that this was due to UdonSharp being an old 0.20 version. I installed VCC and got it to version 1.1.6, however, now it does not show the "Auto-Configure USharpVideo" like the guide shows in the docs on the website. It just says "Re-Detect AudioLink".

![image](https://user-images.githubusercontent.com/7909209/212980312-20147609-ebc5-4f2d-9f3e-9ba1c7be1d45.png)

**Comment by PiMaker** [comment]
Do you have a working U# video player in your scene? Generally, for troubleshooting check out the discord server linked in the docs and the readme!

**Comment by dark-swordsman** [comment]
Apologies, I solved the issue and forgot to come back here.

I downgraded my VRC Base and VRC World packages from 3.1.10 to 3.1.9. Then re-upgraded them back to 3.1.10. I did this because the USharpVideo player was also not working properly.

After reimporting USharpVideo and spawning a new prefab, the player works and LTCGI was able to find the video player.
