### ISSUE TITLE
Popup message bug

### ISSUE THREAD

**Issue by z3y** [PiMaker/ltcgi#18]
![image](https://github.com/PiMaker/ltcgi/assets/33181641/c46b114a-2084-48a3-956d-82a4f9f2fc48)
Dragging the ltcgi prefab into the scene creates a popup message you cant close and it freezes the unity editor. After adding U# into the project the popup still kept appearing, the UDONSHARP define got added but the code from ltcgi didnt recompile with it. It worked only after removing and adding back the ltcgi package. It also kept appearing 2 times after, when switching the build platform, that but i was able to close it and it worked

Not sure if there is a fix for that as its probably a unity bug (what might work is a custom define set on the assembly definition), but at least a fix for the popup message would be nice.

**Comment by PiMaker** [comment]
ehhh I'll just remove the popup and put a note in the inspector then. Shouldn't be too hard. Thanks for reporting!

**Comment by PiMaker** [comment]
This should be fixed in the latest releases and show an error box on the controller and debug log instead of a popup.
