### ISSUE TITLE
3rd Area Light Shape (Dome/Half Sphere)

### ISSUE THREAD

**Issue by Zendrex** [PiMaker/ltcgi#19]
So I know this is going to be an weird and very specific request, however I'm currently working on a fulldome/domemaster project and I would love to include this if I can get it functioning right. I've attached a test video below as to what I am doing to help explain this very specific use case I have. I've tinkered around with the cylinder method and got *a* result but nothing close to what I was hoping to figure out, thus the request for a sphere/halfsphere/dome shape (if at all possible). No harm if it isn't something that can be done with relative ease and is a declined request, just thought I would ask!

Using version 1.3.2 w/ ProTV as the VideoPlayer.

https://github.com/PiMaker/ltcgi/assets/6165571/b08cabb9-dc51-44fa-81fb-e3917780db75

**Comment by PiMaker** [comment]
More shapes are technically possible, yes, but will need a new LTC algorithm derivation. Cylinders use a hack right now which can reuse the rectangular derivation. There are papers on that available, but I don't have the time or muse to implement those right now, sorry.

**Comment by JotaPe** [comment]
[Thttps://github.com/Paul180297/BezierLightLT](https://github.com/Paul180297/BezierLightLTC) I think you would like to take a look at this paper for a future update 👀

**Comment by PiMaker** [comment]
@JotaPe Interesting indeed, there's a few papers for other derivations as well. As I said though, I don't really have time or muse to work on LTCGI right now, other than easier maintainence stuff here and there. Be my guest to attempt to port that code though, it looks decently performance expensive but it does come with a CC-BY-NC-SA license.
