### ISSUE TITLE
Non-US regional settings for decimal separator cause FormatException with float.parse()

### ISSUE THREAD

**Issue by TysonCross** [PiMaker/ltcgi#2]
Solution may be to modify  LTCGI_ControllerExternal.cs (line 187) to read:

` var valueInConfig = float.Parse(line.Substring(line.LastIndexOf(' ')).Replace('f', ' '), System.Globalization.CultureInfo.InvariantCulture);`

**Comment by PiMaker** [comment]
fixed in 34f9806547 and v0.9.3.

Thanks for reporting!
