### ISSUE TITLE
Shaders reading from the wrong path when downloading from VPM

### ISSUE THREAD

**Issue by astridbunny** [PiMaker/ltcgi#21]
Tried both Filamented and Orels shaders, but enabling LTCGI on either gives me an error as they try to pull the shaders from `Assets/_pi_/_LTCGI/Shaders/` when LTCGI is located under `Packages/LTCGI/Shaders/`

**Comment by PiMaker** [comment]
The LTCGI controller script automatically places a compatibiliity shim in the legacy directory. Please check the console for any compilation errors, or try dragging the LTCGI_Controller prefab into your hierarchy first. I have successfully tested the VPM version with the shaders you mention without any issues.

**Comment by astridbunny** [comment]
This works, thanks!
