### ISSUE TITLE
Cache and allow access of global state in LTCGI_UdonAdaptor

### ISSUE THREAD

**Issue by Janooba** [PiMaker/ltcgi#23]
In order to display feedback for options panels controlling the enabled state of LTCGI, I've had to modify the UdonAdaptor to cache the enabled state and provide a getter for it.

Here's what I've done:

```
    private bool isGlobalStateEnabled = true;
    public bool GlobalStateEnabled
    {
        get => isGlobalStateEnabled;
    }
```

```
    public void _SetGlobalState(bool enabled)
    {
        float fstate = enabled ? 1.0f : 0.0f;
        GlobalShader.SetGlobalFloat(GlobalShader.PropertyToID("_Udon_LTCGI_GlobalEnable"), fstate);
        isGlobalStateEnabled = enabled;
    }
```

Super super simple, but helps a lot. If there's a better or different way to access this value I missed, let me know.
Thanks!

**Comment by PiMaker** [comment]
Version v1.4.1 (https://github.com/PiMaker/ltcgi/releases/tag/v1.4.1) available via VCC adds a function `_GetGlobalState()` to the Udon adapter that does what you describe. Hope it helps!
