### ISSUE TITLE
Due missing Play mode, SDK 3.3.0 seems don't generate LTCGI effect.

### ISSUE THREAD

**Issue by MrDummyNL** [PiMaker/ltcgi#24]
After many tries in new SDK 3.3.0 where Play mode is not more needed, LTCGI seems not work anymore, no visible effect, because script generate also in runtime for build & upload. 

Maybe i miss something, but last tests showed no more effect on walls.
Can you take a look at it?

**Comment by PiMaker** [comment]
Hm, do you have any errors in the Unity console or anything to point to specifically? I just tested with SDK 3.3.0 and had no issues, I also don't see how it would cause any problems. It only relies on the pre-build hook that still is executed just fine, playmode was never used for LTCGI uploading.
