### ISSUE TITLE
Unity 2022 Not working as intended?

### ISSUE THREAD

**Issue by JotaPe** [PiMaker/ltcgi#27]
So after VRChat updated to 2022, I tried to upload my world and LTCGI is not working anymore. I think it could have something to do with the lack of play mode during build. So it's more a SDK 3.3.0 problem, than 2022, but because 3.3.0 is old already, I will report as a 2022 problem.

What's the issue: LTCGI doesn't affect third-party shaders (orels, Mochie and Fillament tested) unless there's a single LTCGI_Screen set as dynamic

Video Player: VideoTXL, but it's not only video texture being affected, static textures too and emitters.

There's a workaround, if you have a single dynamic screen all the other ones even if it's set to static start working again. But only on editor.
Avatar lighting still work (dynamic disables it?). So I don't know what's the culprit for it, or if it's a issue caused by my own Unity setup.

**Comment by PiMaker** [comment]
I've tested LTCGI in Unity 2022 without issues, including with latest SDKs. Not sure what you are running into there.

**Comment by JotaPe** [comment]
I think my issue is with some shaders breaking, I'm investigating it.

**Comment by JotaPe** [comment]
Found out was a scene bug, probably broken asset bundles were corrupting the scene, after a full refresh of the project I figured out a fix.
