### ISSUE TITLE
Maybe this needs an update pass for 2022?

### ISSUE THREAD

**Issue by ShiguriVR** [PiMaker/ltcgi#28]
I've run into issues trying to install this to a 2022 project, I'll give you a rundown of what the issues are but I think the TL;DR is going to be to just ask you to install LTCGI to a fresh 2022 project and fix the issues that arise.

The following occurred in a completely fresh project made with the VRCCC.
LTCGI 1.4.1 was installed via the VRCCC method.

**1.)** First, this dialogue, which I'll press "Confirm" on.
![image](https://github.com/PiMaker/ltcgi/assets/85214506/88a1d552-22f9-4e30-8dd0-30b084869fb5)

**2.)** Next, upon attempting to open the new project, this warning dialogue from Unity. I am going to click "Yes, for these and other files that may be found later" because otherwise it pops up every time the project is opened. Note that the next few issues arise even if you click "No" anyway.
![image](https://github.com/PiMaker/ltcgi/assets/85214506/e5aed99b-618c-4e34-939a-1a35e82c308e)

**3.)** When trying to drag the LTCGI Controller prefab into the scene (VRCDefaultWorldScene), shader compile errors are thrown and then these shaders are thrown into the "Failed to Compile" list category in Unity when selecting shaders on a material.
![image](https://github.com/PiMaker/ltcgi/assets/85214506/bfd6cb64-1709-4a52-b27a-1a667365ea96)
![image](https://github.com/PiMaker/ltcgi/assets/85214506/df621b0b-8ca7-4412-9c79-acfe140c3fb2)

**4.)** I thought "okay, so LTCGI shaders are borked, fine, I'll just use something else" and imported Orel's shaders.
However I then found that while in this state the LTCGI variant of Orel's shader also fails to compile...
![image](https://github.com/PiMaker/ltcgi/assets/85214506/b3335dce-efca-4dfd-9800-25dec6cf1655)

**5.)** Okay, so now I knew this is an issue that needs addressed if I want LTCGI to work.

Now I'm no programmer, but upon inspection it appears that in the file it's complaining about, "LTCGI_config.cginc", there's a line that says "not-available".
![image](https://github.com/PiMaker/ltcgi/assets/85214506/986ba73e-b279-41ba-8445-2e5244485cd0)

This text just looked out of place to me, and as if it's a placeholder text that Unity substituted in upon reaching an error. So I looked into the repository for the original code and, sure enough, this is what's supposed to be there.
![image](https://github.com/PiMaker/ltcgi/assets/85214506/2c13ea33-a3b8-46ee-b986-7b62e2a4465f)

So I first tried just changing the "not-available" text to that URL, but Unity would keep changing it back to "not-available" automatically. Clearly it was unhappy with the absence of something, and that something was probably AudioLink.

So I tried installing AudioLink and, sure enough, the issues went away. So the only solution was to actually install AudioLink to the project. If you do that, that line in the LTCGI_config.cginc will change to the AudioLink URL on its own and the shaders will succeed to compile. Removing AudioLink will cause the shader compile errors to resurface.

---

As far as I'm aware, AudioLink isn't intended to be a dependency for LTCGI.
If it is, well I couldn't find anything in the repo or documentation to suggest that.
So if this isn't intended behavior, definitely look into doing an update pass for LTCGI.

I figured these may just be issues that arose with the 2022 upgrade that just haven't been addressed yet.

There may be other bugs that I just haven't found, I don't know what everything is *supposed* to look and behave like so I have no frame of reference for just visually telling whether anything is wrong or not. So definitely poke around and make sure it's working as intended in 2022.

Thanks.

**Comment by PiMaker** [comment]
Fixed in v1.5.0!
