### ISSUE TITLE
LTCGI with out udon

### ISSUE THREAD

**Issue by racushstrago** [PiMaker/ltcgi#3]
I would like to request a version of ltcgi that could possibly work in a standalone form with out the udon side of it or use on other platforms that lack it.  Possibly a sdk2 port or just something that works in any unity project.

**Comment by PiMaker** [comment]
I might make a non-vrchat version available in the future, for general Unity projects.
LTCGI will never support sdk2 however, both for technical limitations and because I don't believe there's much merit to it.

**Comment by XeonG** [comment]
Would really like to see a LTCGI without Udon.. was just looking at trying it out with orels1 shaders (no idea if they are worth using yet or something else LTCGI supports?), and got bogged down in the number of errors that required Udon and VRCHATs sdk.. bit of a shame.. seems pretty good and Unity's BRIP still remaining pretty decent to use compared the URP/HDRP trainwrecks
