### ISSUE TITLE
(Custom VR Game, Unity 2021.3.23f1) LTCGI_RuntimeAdapter class not found OR mismatch

### ISSUE THREAD

**Issue by JOELwindows7** [PiMaker/ltcgi#30]
# LTCGI_RuntimeAdapter class not found OR mismatch
According to the file `<UNITY_PROJECT>/Library/PackageCache/at.pimaker.ltcgi@14b23485f4/Runtime/LTCGI_UdonAdapter.cs`, there is already statement from line 16: 
```
#if UDONSHARP
[UdonBehaviourSyncMode(BehaviourSyncMode.None)]
public class LTCGI_UdonAdapter : UdonSharpBehaviour
#else
// FIXME: This makes the filename mismatch the class name
// - I think Unity doesn't like that?
public class LTCGI_RuntimeAdapter : MonoBehaviour
#endif
```

Yes, Unity `2021.3.23f1` does not like that.

## Screenshots
![script not assigned properly](https://github.com/PiMaker/ltcgi/assets/7281060/4f12e2da-2c48-4571-8ee3-a754a0f688f4)
![out of prefab script said not found](https://github.com/PiMaker/ltcgi/assets/7281060/c44e27e8-90c9-40c7-8bd5-c8a5312fa732)
![image](https://github.com/PiMaker/ltcgi/assets/7281060/2e092e9b-412f-4e25-b14d-583659bc00c0)

The UdonAdapter class indeed transformed into regular Runtime Adapter class. However, due to some nature of C# (perhaps?), the filename must match with its class name.

Therefore currently it only works (maybe?) for VRChat & perhaps not standalone nor any other VR games, since the file name of the adapters combined to or propagated for is `LTCGI_UdonAdapter.cs`, while the converted to regular class name is `LTCGI_RuntimeAdapter : MonoBehaviour` (different than filename).

## Workaround

Possible workaround & patch?:

**Separate those adapters to each respective filename**

- Transplant. Copy whole Udon Adapter class into a new file `LTCGI_RuntimeAdapter.cs` next by UdonAdapter file. 
- Scrub. scrub both these file so the Udon ones only activates if there is UdonSharp installed per `#if UDONSHARP`. And the regular runtime ones only activates if there is no UdonSharp per `#if !UDONSHARP`.
- This should make class query work since now the class names matches with their filename.

Or maybe, keep UdonAdapter name, while when Udon is not installed it acts as regular Runtime Adapter?

**Comment by PiMaker** [comment]
In v1.5.0, `LTCGI_RuntimeAdapter` has been renamed to `LTCGI_UdonAdapter` in the non-VRChat use-case as well. This should fix this. Note however, that it also requires Unity 2022.3 at the minimum now. You can probably backport it to 2021 though if you need to.

**Comment by JOELwindows7** [comment]
> In v1.5.0, `LTCGI_RuntimeAdapter` has been renamed to `LTCGI_UdonAdapter` in the non-VRChat use-case as well. This should fix this. Note however, that it also requires Unity 2022.3 at the minimum now. You can probably backport it to 2021 though if you need to.

## Fix confirmed
![image](https://github.com/PiMaker/ltcgi/assets/7281060/78597ac9-3ab5-42ec-85ca-c17edd81444c)
Yey fixed!

## Attempted backport to 2021 for ChilloutVR
for commit https://github.com/PiMaker/ltcgi/commit/b994fbe846935749882cdb2fa84441807709c828 , file ``Editor/LTCGI_Controller.cs` line 138. Change back to `if (UnityEditor.SceneManagement.EditorSceneManager.loadedSceneCount == 0)` for 2021 scene management is still `UnityEditor.SceneManagement.EditorSceneManager` instead of the merged `UnityEngine...SceneManager`.
