### ISSUE TITLE
LTCGI with ProTV: 'VideoManagerV2' does not contain a definition for 'screens'

### ISSUE THREAD

**Issue by quiesler** [PiMaker/ltcgi#32]
When I import LTCGI 1.5.0 and ProTV 3.0.0-beta.16 (Unity 2022.3.6f1) i get following error:

![image](https://github.com/PiMaker/ltcgi/assets/129618029/2f6f96df-52c7-4600-b50e-fb6007b93712)

VideoManagerV2 is not used anymore in the new Version of ProTV. It uses VPManager now.

**Comment by rhaamo** [comment]
On a new project with same versions (but LTCGI from Creator Companion) I don't even get anything created in `Assets/_pi_/_LTCGI-Adapters/` even if I properly import and put a ProTV in my scene before importing LTCGI, and in the packages folder all adapters are `.disabled_`

**Comment by techanon** [comment]
ProTV 3 auto deletes the protv adapters folder automatically when importing via vcc.
If you imported with another method, you will need to delete the adapter folder entirely as ProTV 3 does not use the adapter at all. https://protv.dev/guides/ltcgi for more info.
