### ISSUE TITLE
LTCGI doesn't behave with UdonSharp 1.0.1 via Creator Companion

### ISSUE THREAD

**Issue by BluWizard10** [PiMaker/ltcgi#4]
When attempting to install the latest LTCGI package, it throws a large compiling error in the console. Says it does not belong to a U# assembly?

This was tested with SDK 3.0.9 and UdonSharp 1.0.1 via the Creator Companion.

**Comment by BluWizard10** [comment]
See attached image for more info about the failed U# assembly warning:
![Unity_4bYONznGAf](https://user-images.githubusercontent.com/17975114/176553943-7c7a18fe-936a-4f6d-9469-a7dcde47e14d.png)

**Comment by PiMaker** [comment]
This is already fixed in the current dev release. You can try it from the [Actions Tab](https://github.com/PiMaker/ltcgi/actions).
