### ISSUE TITLE
odd behavior when using multiple screens with exclusionary renderer lists

### ISSUE THREAD

**Issue by llealloo** [PiMaker/ltcgi#6]
I am having an issue where there is always at least one screen that will ignore its affected renderer exclusion settings. This happens with more than one mesh renderer and each with it's own screen.

**Comment by llealloo** [comment]
actually this is just in editor, during runtime it excludes appropriately

**Comment by PiMaker** [comment]
Fixed with 6f895700696c4ae9fbe5d6acabf73c81410c454d
